### ISSUE TITLE
Library libcublas.so.12 is not found

### ISSUE THREAD

**Issue by hotsource59** [winstxnhdw/nllb-api#111]
Hi,
I recently tried to build this with GPU support. Building the docker image was no problem. When accessing the API there is an error

```python
| Traceback (most recent call last):
    |   File "/usr/local/lib/python3.12/site-packages/starlette/responses.py", line 260, in wrap
    |     await func()
    |   File "/usr/local/lib/python3.12/site-packages/starlette/responses.py", line 249, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/usr/local/lib/python3.12/site-packages/starlette/concurrency.py", line 65, in iterate_in_threadpool
    |     yield await anyio.to_thread.run_sync(_next, as_iterator)
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    |     return await future
    |            ^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    |     result = context.run(func, *args)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/starlette/concurrency.py", line 54, in _next
    |     return next(iterator)
    |            ^^^^^^^^^^^^^^
    |   File "/home/user/app/server/features/translator.py", line 62, in <genexpr>
    |     return (
    |            ^
    |   File "/usr/local/lib/python3.12/site-packages/ctranslate2/extensions.py", line 82, in translator_translate_iterable
    |     yield from _process_iterable(
    |   File "/usr/local/lib/python3.12/site-packages/ctranslate2/extensions.py", line 554, in _process_iterable
    |     yield queue.popleft().result()
    |           ^^^^^^^^^^^^^^^^^^^^^^^^
    | RuntimeError: Library libcublas.so.12 is not found or cannot be loaded
```

I traced it down to a missing Cuda 12 library. The image explicitly uses Cuda 11.8. I tried updating the image to Cuda 12 but that results in other errors.

How do I make it work?

This is my `nvidia-smi` output. The Nvidia docker toolkit is also installed.
```bash
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3080        Off | 00000000:3B:00.0 Off |                  N/A |
| 30%   29C    P5              37W / 320W |    674MiB / 10240MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1288      G   /usr/lib/xorg/Xorg                          324MiB |
|    0   N/A  N/A      1761      G   /usr/bin/kwin_x11                            77MiB |
|    0   N/A  N/A      1820      G   /usr/bin/plasmashell                         94MiB |
|    0   N/A  N/A      1868      G   ...irefox/3836/usr/lib/firefox/firefox      149MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by winstxnhdw** [comment]
Hey, it seems like `ctranslate2` recently added support to CUDA 12. Give me a day to complete the migration here as well.

**Comment by winstxnhdw** [comment]
Hey @hotsource59, I forgot to ping here but I have completed the migration 6 hours ago. Let me know if you still have any issues and if there isn't, we can close this.
